CREATE TABLE GENIE_PAGE (
	PAGE_ID	VARCHAR2(100),
	TITLE		VARCHAR2(100),
	PARAM1	VARCHAR2(100),
	PARAM2	VARCHAR2(100),
	PARAM3	VARCHAR2(100),
	PRIMARY KEY (PAGE_ID)
)
/

CREATE TABLE GENIE_PAGE_SQL (
	PAGE_ID	VARCHAR2(100),
	SEQ		NUMBER(3),
	TITLE		VARCHAR2(100),
	SQL_STMT	VARCHAR2(1000),
	INDENT	NUMBER(3)		DEFAULT 0,
	PRIMARY KEY (PAGE_ID, SEQ),
	FOREIGN KEY (PAGE_ID) REFERENCES GENIE_PAGE ON DELETE CASCADE
)
/

